[workspace]
authors = ["Neppel Elian <elian.neppel@posteo.eu>"]
channels = [ "conda-forge", "https://prefix.dev/motion-stack"]
name = "ros_idl"
platforms = ["linux-64"]
version = "0.1.0"

[feature.noros.tasks]
main = "python main.py"
scan = "python ./query_scan.py -s '**' --add-matching-listener -t 'ALL'"

[feature.jazzy.tasks]
publish = "ros2 topic pub '/not_ros_sub' std_msgs/msg/String '{data: 'Hello_World'}'"
listen = "ros2 topic echo '/not_ros_pub'"
router = "RUST_LOG=debug ros2 run rmw_zenoh_cpp rmw_zenohd"

### Global Tools ####
[dependencies]

[environments]
default = { features = ["pyproject", "jazzy"] } # ROS 2 application and test environment
noros = {features = ["noros", "pyproject"]}

### Python Project ####
[feature.pyproject.dependencies]
numpy = ">=2.4.2,<3"
asyncio_for_robotics = ">=1.3.5,<2"

[feature.pyproject.pypi-dependencies]
cyclonedds = ">=0.10.5, <0.11"
eclipse-zenoh = ">=1.7.2, <2"

[feature.noros]

[feature.noros.dependencies]
python = "3.12.*" # cannot user newer because of cyclonedds, sadge

### ROS 2 Jazzy ####
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
python = ">=3.12.13,<3.15"
lark-parser = ">=0.12.0,<0.13"
ros-jazzy-ros-core = ">=0.11.0,<0.12"
ros-jazzy-ros2cli = ">=0.32.8,<0.33"
ros-jazzy-rmw-zenoh-cpp = ">=0.2.9,<0.3"

[activation.env]
RMW_IMPLEMENTATION="rmw_zenoh_cpp"
ROS_DOMAIN_ID="0"
ROS_AUTOMATIC_DISCOVERY_RANGE="LOCALHOST"
ZENOH_ROUTER_CONFIG_URI="./router.json5"
ZENOH_SESSION_CONFIG_URI="./client.json5"
ROS_LOCALHOST_ONLY=""
