[workspace]
authors = ["Neppel Elian <elian.neppel@posteo.eu>"]
channels = [ "https://prefix.dev/conda-forge"]
name = "PyZeROS2"
platforms = ["linux-64"]
version = "0.1.0"

### Global Tools ####
[dependencies]
python = ">=3.12.13"

[environments]
default = {features = ["pyproject", "ros-z"]}
ros = { features = ["jazzy"] }
dev = {features = ["dev", "jazzy", "dev-ros-z", "pyproject"]}

[feature.pyproject.tasks]
example = "python -m pyzeros.example"
demo = "python -m pyzeros.demo"
router = "RUST_LOG=debug zenohd -c ./router.json5"

[feature.dev.tasks]
pytest = "pytest"
bench = "python ./tests/bench/pyzeros_bench.py"


[feature.pyproject.dependencies]
# cyclonedds doesn't like python3.14
python = "<3.14"
zenohd = ">=1.7.2,<2"

[feature.pyproject.pypi-dependencies]
pyzeros = {path = ".", editable = true}
cyclonedds-nightly = ">=2026.3.5, <2027"
asyncio_for_robotics = ">=1.3.5, <2"
ros2_pyterfaces = ">=0.2.0"
# ros2_pyterfaces ={path = "./../ros2-pyterfaces/", editable = true}
cydr = ">=0.1.3"
# cydr = {path="./../cydr/", editable=true}
cyclonedds_idl = "*"

[feature.ros-z.pypi-dependencies]
ros_z_msgs_py = {subdirectory = "crates/ros-z-msgs/python/", git = "https://github.com/2lian/ros-z", rev= "99fd7fa567921ace4017dea6c25243a867183fc7"}
ros_z_py = {subdirectory = "crates/ros-z-py/", git = "https://github.com/2lian/ros-z", rev= "99fd7fa567921ace4017dea6c25243a867183fc7"}

### ROS 2 Jazzy ####
# isolated. For asserting interop with normal ROS 2
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
lark-parser = ">=0.12.0,<0.13"
ros-jazzy-ros-core = ">=0.11.0,<0.12"
ros-jazzy-ros2cli = ">=0.32.8,<0.33"
ros-jazzy-rmw-zenoh-cpp = ">=0.2.9,<0.3"

### Dev tools ####
[feature.dev.dependencies]
# maturin doesn't like python3.14
python = "<3.14"
uv = "*"
pyright = "*"
isort = "*"
black = "*"
rust = ">=1.94.0,<1.95"
maturin = ">=1.12.6,<2"
glow-md = "*"
pytest = ">=9.0.2,<10"
mypy = ">=1.19.1,<2"
pytest-asyncio = ">=1.3.0,<2"
uvloop = ">=0.22.1,<0.23"
plotly = ">=6.6.0,<7"
pyinstrument = ">=5.1.2,<6"

[feature.dev.pypi-dependencies]
eclipse-zenoh = ">=1.8.0, <2"

[feature.dev-ros-z.pypi-dependencies]
ros_z_msgs_py = {path = "ros-z/crates/ros-z-msgs/python/", editable = true}
ros_z_py = {path = "ros-z/crates/ros-z-py/", editable = true}


### Env variables ###
[activation.env]
RMW_IMPLEMENTATION="rmw_zenoh_cpp"
ROS_DOMAIN_ID="0"
ROS_AUTOMATIC_DISCOVERY_RANGE="LOCALHOST"
ZENOH_ROUTER_CONFIG_URI="./router.json5"
ZENOH_SESSION_CONFIG_URI="./client.json5"
ROS_LOCALHOST_ONLY=""
PYTHON_GIL="1"

### Env variables ###
[feature.dev.activation.env]
# ZENOH_SHM_ALLOC_SIZE="52428800"
# ZENOH_SHM_MESSAGE_SIZE_THRESHOLD="10000"
